spring.application.name=daily-tracker


gemini.api.key=AIzaSyAqOhGUz5E0NMfeu-LjQJc4yM6toyHSWIc
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

openrouter.api.key=${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}
spring.mvc.async.request-timeout=30000